from __future__ import annotations

import json
from pathlib import Path
import re
import shutil
import subprocess
import sys

import pytest


ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "fixtures"


def run_cli(root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "specbound.cli", "--root", str(root), *args],
        cwd=ROOT,
        env={"PYTHONPATH": str(ROOT / "src")},
        check=False,
        capture_output=True,
        text=True,
    )


def payload(result: subprocess.CompletedProcess[str]) -> dict:
    return json.loads(result.stdout)


def copied_fixture(tmp_path: Path) -> Path:
    target = tmp_path / "repo"
    shutil.copytree(FIXTURES / "valid-minimal", target)
    return target


def test_docs_requirements_generates_a_friendly_latest_requirement_index(tmp_path: Path) -> None:
    root = copied_fixture(tmp_path)
    requirement = root / ".specbound/requirements/req-0001/req-0001-r1.md"
    approval = root / ".specbound/approvals/req-0001-r1.approval.json"
    canonical_before = (requirement.read_bytes(), approval.read_bytes())

    result = run_cli(root, "docs", "requirements")

    assert result.returncode == 0, result.stdout
    body = payload(result)
    assert body == {
        "changed": True,
        "requirements": 1,
        "requirements_document": "docs/requirements.md",
        "valid": True,
    }
    document = (root / "docs/requirements.md").read_text(encoding="utf-8")
    assert document.startswith("<!-- Generated by SpecBound. Do not edit directly. -->")
    assert "# 요구사항 명세 목록" in document
    assert "최소 유효성 검증 요구사항" in document
    assert "승인된 요구사항과 증거의 정확한 결합을 검증합니다." in document
    assert "[REQ-0001 r1](../.specbound/requirements/req-0001/req-0001-r1.md)" in document
    assert "제공됨" in document
    assert "sha256" not in document.lower()
    assert "authority" not in document.lower()
    assert (requirement.read_bytes(), approval.read_bytes()) == canonical_before


def test_docs_requirements_check_detects_a_stale_document_without_rewriting(tmp_path: Path) -> None:
    root = copied_fixture(tmp_path)
    generated = run_cli(root, "docs", "requirements")
    assert generated.returncode == 0, generated.stdout
    document = root / "docs/requirements.md"
    document.write_text(document.read_text(encoding="utf-8") + "\n수동 변경\n", encoding="utf-8", newline="\n")
    before = document.read_bytes()

    result = run_cli(root, "docs", "requirements", "--check")

    assert result.returncode == 2, result.stdout
    assert payload(result) == {
        "blockers": [
            {
                "code": "stale_requirements_document",
                "detail": "run 'specbound docs requirements' to regenerate the user-facing requirement index",
                "path": "docs/requirements.md",
            }
        ],
        "valid": False,
    }
    assert document.read_bytes() == before


def test_docs_requirements_is_idempotent_when_document_is_current(tmp_path: Path) -> None:
    root = copied_fixture(tmp_path)
    first = run_cli(root, "docs", "requirements")
    second = run_cli(root, "docs", "requirements")
    checked = run_cli(root, "docs", "requirements", "--check")

    assert first.returncode == 0, first.stdout
    assert second.returncode == 0, second.stdout
    assert payload(second)["changed"] is False
    assert checked.returncode == 0, checked.stdout
    assert payload(checked) == {
        "requirements": 1,
        "requirements_document": "docs/requirements.md",
        "valid": True,
    }


def test_docs_requirements_selects_the_latest_numeric_revision(tmp_path: Path) -> None:
    root = copied_fixture(tmp_path)
    original = root / ".specbound/requirements/req-0001/req-0001-r1.md"
    revision = original.parent / "req-0001-r2.md"
    revision.write_text(
        original.read_text(encoding="utf-8")
        .replace("revision: 1", "revision: 2", 1)
        .replace("title: 최소 유효성 검증 요구사항", "title: 최신 사용자 요구사항", 1)
        .replace("status: approved", "status: draft", 1),
        encoding="utf-8",
        newline="\n",
    )

    result = run_cli(root, "docs", "requirements")

    assert result.returncode == 0, result.stdout
    document = (root / "docs/requirements.md").read_text(encoding="utf-8")
    assert "[REQ-0001 r2](../.specbound/requirements/req-0001/req-0001-r2.md)" in document
    assert "최신 사용자 요구사항" in document
    assert "최소 유효성 검증 요구사항" not in document
    assert "초안" in document


def test_docs_requirements_rejects_placeholder_display_metadata(tmp_path: Path) -> None:
    root = copied_fixture(tmp_path)
    requirement = root / ".specbound/requirements/req-0001/req-0001-r1.md"
    requirement.write_text(
        requirement.read_text(encoding="utf-8").replace(
            "title: 최소 유효성 검증 요구사항",
            "title: <사용자 친화적인 요구사항명>",
            1,
        ),
        encoding="utf-8",
        newline="\n",
    )

    result = run_cli(root, "docs", "requirements")

    assert result.returncode == 2, result.stdout
    assert payload(result)["blockers"][0]["code"] == "missing_requirement_display_metadata"
    assert not (root / "docs/requirements.md").exists()


def test_docs_requirements_rejects_a_symlinked_canonical_root(tmp_path: Path) -> None:
    root = copied_fixture(tmp_path)
    canonical = root / ".specbound/requirements"
    outside = tmp_path / "outside-requirements"
    canonical.rename(outside)
    try:
        canonical.symlink_to(outside, target_is_directory=True)
    except OSError as exc:
        pytest.skip(f"symlink creation is unavailable: {exc}")

    result = run_cli(root, "docs", "requirements")

    assert result.returncode == 2, result.stdout
    assert payload(result)["blockers"][0]["code"] == "unsafe_artifact_path"
    assert not (root / "docs/requirements.md").exists()


@pytest.mark.parametrize("symlink_leaf", (False, True))
def test_docs_requirements_rejects_symlinked_projection_path(
    tmp_path: Path, symlink_leaf: bool
) -> None:
    root = copied_fixture(tmp_path)
    outside = tmp_path / "outside-docs"
    outside.mkdir()
    docs = root / "docs"
    try:
        if symlink_leaf:
            docs.mkdir()
            (docs / "requirements.md").symlink_to(outside / "requirements.md")
        else:
            docs.symlink_to(outside, target_is_directory=True)
    except OSError as exc:
        pytest.skip(f"symlink creation is unavailable: {exc}")

    result = run_cli(root, "docs", "requirements")

    assert result.returncode == 2, result.stdout
    assert payload(result)["blockers"][0]["code"] == "unsafe_artifact_path"
    assert not (outside / "requirements.md").exists()


def test_docs_requirements_rejects_nested_noncanonical_requirement_path(tmp_path: Path) -> None:
    root = copied_fixture(tmp_path)
    source = root / ".specbound/requirements/req-0001/req-0001-r1.md"
    nested = root / ".specbound/requirements/nested/req-0001/req-0001-r1.md"
    nested.parent.mkdir(parents=True)
    shutil.copy2(source, nested)

    result = run_cli(root, "docs", "requirements")

    assert result.returncode == 2, result.stdout
    assert payload(result)["blockers"][0]["code"] == "invalid_requirement_path"


@pytest.mark.parametrize(
    ("schema_name", "property_path"),
    (
        ("approval-record.schema.json", ("properties", "requirement_path")),
        ("micro-spec-review-record.schema.json", ("properties", "requirement_path")),
        ("micro-spec.schema.json", ("properties", "requirement", "properties", "path")),
        ("delivery-qc.schema.json", ("properties", "requirement", "properties", "path")),
    ),
)
def test_requirement_binding_schemas_enforce_canonical_root(
    schema_name: str, property_path: tuple[str, ...]
) -> None:
    node = json.loads((ROOT / "schemas" / schema_name).read_text(encoding="utf-8"))
    for component in property_path:
        node = node[component]
    pattern = node["pattern"]

    assert re.fullmatch(pattern, ".specbound/requirements/req-0001/req-0001-r1.md")
    assert not re.fullmatch(pattern, "Xspecbound/requirements/req-0001/req-0001-r1.md")
    assert not re.fullmatch(pattern, "docs/requirements/req-0001/req-0001-r1.md")
