"""Generate the user-facing requirement index from canonical REQ metadata."""

from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
import secrets
import stat
import tempfile

import yaml

from .validation import (
    PLACEHOLDER_RE,
    REQUIREMENT_RE,
    REQUIRED_ROOTS,
    _first_symlink_component,
    _frontmatter,
    canonical_requirement_relative,
)


REQUIREMENTS_DOCUMENT = "docs/requirements.md"
GENERATED_NOTICE = "<!-- Generated by SpecBound. Do not edit directly. -->"
STATUS_LABELS = {
    "draft": "초안",
    "in_review": "검토 중",
    "approved": "제공됨",
    "rejected": "거절됨",
}


@dataclass(frozen=True)
class RequirementsDocumentError(Exception):
    code: str
    path: str
    detail: str

    def __str__(self) -> str:
        return self.detail


def _table_text(value: str) -> str:
    return " ".join(value.split()).replace("|", "\\|")


def _require_display_text(metadata: dict[object, object], field: str, relative: str) -> str:
    value = metadata.get(field)
    if not isinstance(value, str) or not value.strip() or PLACEHOLDER_RE.search(value):
        raise RequirementsDocumentError(
            "missing_requirement_display_metadata",
            relative,
            f"canonical REQ frontmatter must contain a non-empty {field}",
        )
    return _table_text(value)


def render_requirements_document(root: Path) -> tuple[str, int]:
    requirement_root = root / REQUIRED_ROOTS["requirements_root"]
    symlink = _first_symlink_component(root, requirement_root)
    if symlink:
        raise RequirementsDocumentError(
            "unsafe_artifact_path",
            symlink.relative_to(root).as_posix(),
            "canonical requirements root must not contain a symlink",
        )
    if not requirement_root.is_dir():
        raise RequirementsDocumentError(
            "missing_requirements_root",
            REQUIRED_ROOTS["requirements_root"],
            "canonical requirements root does not exist",
        )

    latest: dict[str, tuple[int, Path, dict[object, object]]] = {}
    for path in sorted(requirement_root.rglob("*.md")):
        symlink = _first_symlink_component(root, path)
        if symlink:
            raise RequirementsDocumentError(
                "unsafe_artifact_path",
                symlink.relative_to(root).as_posix(),
                "canonical REQ path must not contain a symlink",
            )
        match = REQUIREMENT_RE.fullmatch(path.name)
        relative = path.relative_to(root).as_posix()
        if not match or path.parent.name != match.group(1):
            raise RequirementsDocumentError(
                "invalid_requirement_path",
                relative,
                "expected req-<id>/req-<id>-r<revision>.md",
            )
        requirement_id, revision_text = match.groups()
        if relative != canonical_requirement_relative(requirement_id, revision_text):
            raise RequirementsDocumentError(
                "invalid_requirement_path",
                relative,
                "expected req-<id>/req-<id>-r<revision>.md directly under the canonical root",
            )
        try:
            metadata = _frontmatter(path)
        except (OSError, ValueError, yaml.YAMLError) as exc:
            raise RequirementsDocumentError("malformed_requirement", relative, str(exc)) from exc
        revision = int(revision_text)
        if metadata.get("id") != requirement_id or metadata.get("revision") != revision:
            raise RequirementsDocumentError(
                "requirement_binding_mismatch",
                relative,
                "frontmatter id/revision differs from path",
            )
        current = latest.get(requirement_id)
        if current is None or revision > current[0]:
            latest[requirement_id] = (revision, path, metadata)

    rows: list[str] = []
    for requirement_id in sorted(latest, key=lambda value: int(value.removeprefix("req-"))):
        revision, path, metadata = latest[requirement_id]
        relative = path.relative_to(root).as_posix()
        title = _require_display_text(metadata, "title", relative)
        summary = _require_display_text(metadata, "summary", relative)
        status = metadata.get("status")
        if status not in STATUS_LABELS:
            raise RequirementsDocumentError(
                "malformed_requirement",
                relative,
                "frontmatter status must be draft, in_review, approved, or rejected",
            )
        link = f"../{relative}"
        label = f"{requirement_id.upper()} r{revision}"
        rows.append(f"| [{label}]({link}) | {title} | {summary} | {STATUS_LABELS[status]} |")

    body = "\n".join(
        [
            GENERATED_NOTICE,
            "",
            "# 요구사항 명세 목록",
            "",
            "SpecBound가 관리하는 최신 요구사항을 사용자 관점에서 정리한 문서입니다.",
            "상세한 검증·승인 계약은 각 요구사항의 내부 정규 원본에서 확인할 수 있습니다.",
            "",
            "| ID | 요구사항 | 사용자 관점 설명 | 상태 |",
            "| --- | --- | --- | --- |",
            *rows,
            "",
            "> 이 문서는 `.specbound/requirements/`의 정규 REQ 메타데이터에서 생성됩니다.",
            "",
        ]
    )
    return body, len(rows)


def _replace_document_atomically(root: Path, target: Path, expected: bytes) -> None:
    """Replace the derived document without following a swapped POSIX parent."""
    parent = target.parent
    parent.mkdir(parents=True, exist_ok=True)

    if os.name == "posix" and all(
        hasattr(os, name) for name in ("O_DIRECTORY", "O_NOFOLLOW")
    ):
        directory_fd = os.open(parent, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
        temporary_name: str | None = None
        try:
            for _ in range(100):
                candidate = f".requirements.{secrets.token_hex(8)}.tmp"
                try:
                    descriptor = os.open(
                        candidate,
                        os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW,
                        0o600,
                        dir_fd=directory_fd,
                    )
                except FileExistsError:
                    continue
                temporary_name = candidate
                break
            else:
                raise OSError("could not allocate a unique requirements-document temporary file")

            with os.fdopen(descriptor, "wb") as handle:
                handle.write(expected)
                handle.flush()
                os.fsync(handle.fileno())

            try:
                target_stat = os.stat(target.name, dir_fd=directory_fd, follow_symlinks=False)
            except FileNotFoundError:
                pass
            else:
                if stat.S_ISLNK(target_stat.st_mode):
                    raise RequirementsDocumentError(
                        "unsafe_artifact_path",
                        target.relative_to(root).as_posix(),
                        "generated requirements document must not be a symlink",
                    )

            os.replace(
                temporary_name,
                target.name,
                src_dir_fd=directory_fd,
                dst_dir_fd=directory_fd,
            )
            temporary_name = None
            os.fsync(directory_fd)
        finally:
            if temporary_name is not None:
                try:
                    os.unlink(temporary_name, dir_fd=directory_fd)
                except FileNotFoundError:
                    pass
            os.close(directory_fd)
        return

    # Windows fallback: reject symlinks and verify that the parent identity did
    # not change between allocation and replacement. POSIX uses the stronger
    # descriptor-relative branch above.
    before = os.stat(parent, follow_symlinks=False)
    if stat.S_ISLNK(before.st_mode):
        raise RequirementsDocumentError(
            "unsafe_artifact_path",
            parent.relative_to(root).as_posix(),
            "generated requirements document parent must not be a symlink",
        )
    descriptor, temporary_name = tempfile.mkstemp(prefix=".requirements.", suffix=".tmp", dir=parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(expected)
            handle.flush()
            os.fsync(handle.fileno())
        after = os.stat(parent, follow_symlinks=False)
        if not os.path.samestat(before, after) or stat.S_ISLNK(after.st_mode):
            raise RequirementsDocumentError(
                "unsafe_artifact_path",
                parent.relative_to(root).as_posix(),
                "generated requirements document parent changed during publication",
            )
        if target.is_symlink():
            raise RequirementsDocumentError(
                "unsafe_artifact_path",
                target.relative_to(root).as_posix(),
                "generated requirements document must not be a symlink",
            )
        os.replace(temporary, target)
    except (OSError, RequirementsDocumentError):
        temporary.unlink(missing_ok=True)
        raise


def update_requirements_document(root: Path, *, check: bool = False) -> tuple[bool, int]:
    content, count = render_requirements_document(root)
    target = root / REQUIREMENTS_DOCUMENT
    symlink = _first_symlink_component(root, target)
    if symlink:
        raise RequirementsDocumentError(
            "unsafe_artifact_path",
            symlink.relative_to(root).as_posix(),
            "generated requirements document path must not contain a symlink",
        )
    expected = content.encode("utf-8")
    try:
        current = target.read_bytes()
    except FileNotFoundError:
        current = None

    if check:
        if current != expected:
            raise RequirementsDocumentError(
                "stale_requirements_document",
                REQUIREMENTS_DOCUMENT,
                "run 'specbound docs requirements' to regenerate the user-facing requirement index",
            )
        return False, count

    if current == expected:
        return False, count

    _replace_document_atomically(root, target, expected)
    return True, count
